# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbf8af5dce4ef7eb81585fde8541b6f0f781964920cd5dbff8a1ff4ec7b166a3e21b6a0aa1754befe95dacd622f252bf347818a09c43d79846035de3eb6f35be

test:
  secret_key_base: c56f746f6178df5c66a6053d119df10890359b560cded8a48a2273035d8159ea1f337a056293562a85c638e3ae6fa2bca792548d37b4343dbbc1b6ccc341342f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
